version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: fpl_games
      - name: fpl_player_games
      - name: understat_games
      - name: understat_player_games
      - name: fpl_teams
      - name: fpl_players
      - name: fpl_upcoming_games
      - name: fpl_player_teams
  - name: master
    schema: master
    tables:
      - name: player_mappings
      - name: team_mappings
    
    