
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'fpl_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'fpl_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  fpl_dbt:
    staging:
      +schema: staging
      +materialized: view
    core:
      +schema: core
      +materialized: incremental
    master:
      +schema: master
      +materialized: incremental
    analytics:
      +schema: analytics
      +materialized: view

vars:
  player_games_rolling_metrics:
    - points
    - minutes_played
    - goals_scored
    - expected_goals_understat
    - goals_conceded
    - assists
    - expected_assists_understat
    - yellow_cards
    - red_card
    - clean_sheet
    - key_passes
    - own_goals
    - penalties_missed
    - penalties_saved
    - saves
    - bonus_points

seeds:
  fpl_dbt:
    +schema: staging
    fpl_db_core_players:
      +column_types:
        id: uuid
        name: text
        is_active: boolean
    fpl_db_core_teams:
      +column_types:
        id: uuid
        name: text
    fpl_db_core_games:
      +column_types:
        id: uuid
        season: text
        gameweek: integer
        datetime: timestamp
        result: text
        home_team_id: uuid
        away_team_id: uuid
    fpl_db_core_player_games:
      +column_types:
        id: uuid
        player_id: uuid
        game_id: uuid
        fpl_price: integer
        points: integer
        minutes_played: integer
        goals_scored: integer
        expected_goals_understat: double precision
        goals_conceded: integer
        assists: integer
        expected_assists_understat: double precision
        yellow_cards: integer
        red_card: integer
        clean_sheet: integer
        key_passes: integer
        own_goals: integer
        penalties_missed: integer
        penalties_saved: integer
        saves: integer
        bonus_points: integer
        expected_assists_fpl: double precision
        expected_goals_fpl: double precision
        fpl_element: integer
        local_understat_id: integer
    fpl_db_core_player_seasons:
      +column_types:
        id: uuid
        player_id: uuid
        season: text
        position: integer
    fpl_db_core_player_teams:
      +column_types:
        id: uuid
        start_date: timestamp
        end_date: timestamp
        team_id: uuid
        player_id: uuid
    fpl_db_master_game_mappings:
      +column_types:
        game_id: uuid
        season: text
        fpl_game_id: integer
        understat_game_id: integer
    fpl_db_master_player_mappings:
      +column_types:
        id: integer
        player_id: uuid
        season: text
        fpl_seasonal_id: integer
        opta_id: text
        fpl_name: text
        understat_name: text
        position: integer
    fpl_db_master_team_mappings:
      +column_types:
        id: integer
        team_id: uuid
        season: text
        fpl_team_id: integer
        fpl_name: text
        understat_name: text
# seeds:
#   fpl_dbt:
#     fpl_db_core_players:
#       +column_types:
#         id: uuid
#         name: string
#         is_active: boolean
#     fpl_db_core_teams:
#       +column_types:
#         id: uuid
#         name: string
#     fpl_db_core_games:
#       +column_types:
#         id: uuid
#         season: string
#         gameweek: integer
#         datetime: datetime
#         result: string
#         home_team_id: uuid
#         away_team_id: uuid
#     fpl_db_core_player_games:
#       +column_types:
#         id: uuid
#         player_id: uuid
#         game_id: uuid
#         fpl_price: integer
#         points: integer
#         minutes_played: integer
#         goals_scored: integer
#         expected_goals_understat: float
#         goals_conceded: integer
#         assists: integer
#         expected_assists_understat: float
#         yellow_cards: integer
#         red_card: integer
#         clean_sheet: integer
#         key_passes: integer
#         own_goals: integer
#         penalties_missed: integer
#         penalties_saved: integer
#         saves: integer
#         bonus_points: integer
#         expected_assists_fpl: float
#         expected_goals_fpl: float
#         fpl_element: integer
#         local_understat_id: integer
#     fpl_db_core_player_seasons:
#       +column_types:
#         id: uuid
#         player_id: uuid
#         season: string
#         position: integer
#     fpl_db_core_player_teams:
#       +column_types:
#         id: uuid
#         start_date: datetime
#         end_date: datetime
#         team_id: uuid
#         player_id: uuid
#     fpl_db_master_game_mappings:
#       +column_types:
#         game_id: uuid
#         season: string
#         fpl_game_id: integer
#         understat_game_id: integer
#     fpl_db_master_player_mappings:
#       +column_types:
#         id: integer
#         player_id: uuid
#         season: string
#         fpl_seasonal_id: integer
#         opta_id: integer
#         fpl_name: string
#         understat_name: string
#         position: string
#     fpl_db_master_team_mappings:
#       +column_types:
#         id: integer
#         team_id: uuid
#         season: string
#         fpl_team_id: integer
#         fpl_name: string
#         understat_name: string